### ISSUE TITLE
Please delete attribute FInal from classes!

### ISSUE THREAD

**Issue by dissonancephp** [Nyholm/psr7#168] opened 2021-01-14 20:49 UTC
I need to extend the class

**Comment by mahagr** [comment] 2021-01-15 07:10
See https://github.com/Nyholm/psr7/issues/139

**Comment by dissonance-php** [comment] 2021-01-17 00:39
The standard describes recommended basic interaction interfaces, and your solution provides the basic solution. I think many people understand that decoration is better than inheritance, but in this case there is a problem of creating an object for the sake of an object and an unnecessary description of geters proxying your methods, also decorators make it unclear to understand the code. You have made a solution for mass use, but closing the possibilities for inheritance, without an urgent need, is doubtful. I think it is correct to declare the methods themselves final, and not to touch the class itself.
 #139

**Comment by dissonance-php** [comment] 2021-01-17 22:04
@mahagr   Please publish your traits in a separate package, people will be grateful. I will use it as a temporary solution. In my project, the size of the code is very important, because the application will be compiled into a single file. That is why unnecessary duplication of code is unacceptable for me. Your CMS fits well as an application into the ideology of my my project.

**Comment by Nyholm** [comment] 2021-01-30 12:52
I would be happy to remove the `final` keyword on the classes. The only thing I need is an argument based in computer science and good practices. 

So, could I ask you, why you need to extend the class?

**Comment by withinboredom** [comment] 2021-02-09 11:40
I've been coming up with very intricate solutions around this, 100% in unit tests where I'd like to mock these classes so I can inject failures into my router.

**Comment by Nyholm** [comment] 2021-02-09 12:37
I really do appreciate this idea. Please don't see my as a douchebag that is just trying to make other people's life for no reason. 

> 100% in unit tests where I'd like to mock these classes so I can inject failures into my router.

That is indeed a scenario I can understand your frustration. However, best practice is to mock interfaces. Ie normally in TDD you write the interface, then the test and then actual implementation. 

Also, the classes in this library is value objects, which means you usually don't need to mock them at all.

**Comment by withinboredom** [comment] 2021-02-09 22:10
> That is indeed a scenario I can understand your frustration. However, best practice is to mock interfaces.

To be more precise, these are integration tests. Not unit tests, I don't know why I said unit. :) So basically, I'd only want to mock the part that would trigger a specific error, so other parts of the app can use the actual behavior.

Also, I'd love to be able to extend these classes just to rewind the stream after adding it. Having to remember to do it in every test is fairly annoying. ;)

**Comment by Nyholm** [comment] 2021-02-10 08:04
I dont like it, but I opened a PR =)

#169

**Comment by AndreKR** [comment] 2021-02-16 11:55
@withinboredom @dissonancephp Did you consider using reflection to build mocks?

Just recently I found out about the technique and it turned out to be more convenient than constantly subclassing things to build mocks.

**Comment by withinboredom** [comment] 2021-02-16 14:04
@AndreKR How do you use reflection to change what a function returns?

**Comment by AndreKR** [comment] 2021-02-16 14:30
I find that manipulating private member variables that are then used by the functions is usually enough.

**Comment by Zegnat** [comment] 2021-02-16 14:51
I would mock the interface itself and not depend on an interface implementation for it. Which is often a lot more straightforward and might be part of your testing framework already (e.g. `$this->createMock(\Psr\Http\Message\RequestInterface::class);`).

Though this may not apply to integration testing. Hard to say anything there without diving into the tests. But usually I would be looking at the logic that creates the value object (which a PSR-7 message is an example of) and tweak that to change the actual value object that gets created, rather than after-creation changing the value object itself. As the whole idea with immutable value objects is that they are safe to pass around, and you may be losing that property.

Lots of options, and it will need to be judged on a case-by-case basis what is the easiest and proper way to go. I personally would never recommend extending a value object if other options exist.

But we’ll continue the discussion on dropping `final` from this library in the PR :)

**Comment by AndreKR** [comment] 2021-02-16 15:06
> I would mock the interface itself and not depend on an interface implementation for it.

I was assuming this is out of the question because the code under test type hints _actual class names_. If you just need to provide an interface, you usually wouldn't have any problems and wouldn't need to come here requesting the `open`-ization of the classes. :)

**Comment by withinboredom** [comment] 2021-02-16 20:32
> I personally would never recommend extending a value object if other options exist.

In my case, I have a router that uses many libraries with middleware doing interesting things. I want to simulate a failure seen in production and make sure it's handled correctly without re-implementing the entire library; I should be able to do that. I've been doing this for a long time and don't need to be told what "I should or shouldn't do." TBH, I agree with you, but the system that pays my bills wants to know that this error will be handled correctly, with no regressions, ever.

It actually just occurred to me that the easiest solution would just be to internally fork the repo and maintain a branch without the `final` keyword. In that case, @Nyholm doesn't have to taint his excellent library and I can accomplish what I need to do. ;)

**Comment by Nyholm** [comment] 2021-03-04 07:49
The `final` keyword is removed. However, you should not extend the classes. See https://github.com/Nyholm/psr7/blob/master/doc/final.md

**Closed by Nyholm** 2021-03-04 07:49 UTC

**Comment by dissonancephp** [comment] 2021-03-20 02:12
> The `final` keyword is removed. However, you should not extend the classes. See https://github.com/Nyholm/psr7/blob/master/doc/final.md

Thank you very much! The point was not only to expand, but also to add a specific implementation to my namespaces (/MyVendor/Psr7), so that in the future you can easily switch to your own solution or any other.
